### ISSUE TITLE
Support AS 3.1 and 3.2

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/aker#17]
Aker's gemspec claims support for all 3.x versions of ActiveSupport. It is currently only tested in CI on 3.0.x, however. 

Initial attempts at running Aker's test suite with AS 3.1.3 and 3.2.0.rc1 found no spec failures, but two cucumber failures of this form:

```
ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
./features/support/controllable_cas_server.rb:44:in `register_user'
./features/step_definitions/setup_steps.rb:38:in `block (2 levels) in <top (required)>'
./features/step_definitions/setup_steps.rb:37:in `each'
./features/step_definitions/setup_steps.rb:37:in `/^I have a CAS server that accepts these usernames and passwords:$/'
features/cas.feature:5:in `Given I have a CAS server that accepts these usernames and passwords:'
```

These appear to be test setup failures, rather than actual failures that would be encountered when using Aker with AS 3.1 or 3.2.

**Comment by wjdix** [comment]
After updating [rubycas-server](http://github.com/NUBIC/rubycas-server), All tests and features pass with AS 3.1 and AS 3.2

**Comment by rsutphin** [comment]
The CI builds have been failing ever since the fixes for this were merged.

**Comment by rsutphin** [comment]
Update: the CI build is now passing for all rubies on AS 3.0 and 3.1. It passes for JRuby and MRI 1.8.7 on AS 2.3, but not 1.9.2. I'm okay with this because the set of people using Rails 2.3 with Ruby 1.9.2 has got to be pretty close to empty at this point.

Neither 1.8.7 or 1.9.2 builds pass with AS 3.2, however, so I have not enabled 3.2 in CI.
